"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Caroline Zhuang, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: cz7828
"""

def length_of_longest_substring_n3(s):
    """
    Finds the length of the longest substring without repeating characters
    using a brute force approach (O(N^3)).

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    max_length = 0
    n = len(s)
    for start in range(n):
        for end in range(start, n):
            freq_list = [0] * 256
            substr = s[start:end + 1]
            for char in substr:
                char_index = ord(char)
                freq_list[char_index] += 1
            if all(count <=1 for count in freq_list):
                max_length = max(max_length, end - start +1)
    return max_length

def length_of_longest_substring_n2(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N^2)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    max_length = 0
    n = len(s)
    for start in range(n):
        freq_list = [0] * 256
        for end in range(start,n):
            char_index = ord(s[end])
            freq_list[char_index] += 1
            if all(count <=1 for count in freq_list):
                max_length = max(max_length, end - start +1)
    return max_length

def length_of_longest_substring_n(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list. However, this approach stops early, breaking out of the inner
    loop when a repeating character is found. You may also choose to challenge
    yourself by implementing a sliding window approach.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    n = len(s)
    max_length = 0
    for start in range(n):
        freq_list = [0] * 256
        for end in range(start, n):
            char_index = ord(s[end])
            freq_list[char_index] += 1
            if freq_list[char_index] > 1:
                break
            max_length = max(max_length, end - start + 1)
    return max_length
